// ============================================================
// Fareja – Dados de ~90 raças para seed no Supabase
// ============================================================

export type BreedInsert = {
  name_pt: string;
  name_en: string;
  breed_group: string;
  size: "small" | "medium" | "large" | "giant";
  coat: "short" | "medium" | "long" | "hairless";
  energy_level: number;
  grooming_needs: number;
  trainability: number;
  friendliness: number;
  good_with_kids: boolean;
  good_for_apartments: boolean;
  exercise_needs: number;
  shedding_level: number;
  weight_min_kg: number;
  weight_max_kg: number;
  height_min_cm: number;
  height_max_cm: number;
  life_span_min: number;
  life_span_max: number;
  temperament_pt: string;
  description_pt: string;
  image_url: string | null;
};

export const breedsData: BreedInsert[] = [
  {
    name_pt: "Golden Retriever",
    name_en: "Golden Retriever",
    breed_group: "Esportivo",
    size: "large",
    coat: "medium",
    energy_level: 4,
    grooming_needs: 3,
    trainability: 5,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 3,
    weight_min_kg: 25,
    weight_max_kg: 34,
    height_min_cm: 51,
    height_max_cm: 61,
    life_span_min: 10,
    life_span_max: 12,
    temperament_pt: "Amigável, Confiável, Inteligente, Paciente",
    description_pt: "Um dos cães mais populares do mundo. Extremamente dócil e ideal para famílias com crianças. Precisa de exercício diário e espaço para se mover.",
    image_url: null,
  },
  {
    name_pt: "Labrador Retriever",
    name_en: "Labrador Retriever",
    breed_group: "Esportivo",
    size: "large",
    coat: "short",
    energy_level: 4,
    grooming_needs: 2,
    trainability: 5,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 4,
    weight_min_kg: 25,
    weight_max_kg: 36,
    height_min_cm: 54,
    height_max_cm: 62,
    life_span_min: 10,
    life_span_max: 12,
    temperament_pt: "Bondoso, Extrovertido, Ativo, Gentil",
    description_pt: "Versátil e incrivelmente amigável. Excelente cão de família, guia e resgate. Adora água e precisa de bastante atividade física.",
    image_url: null,
  },
  {
    name_pt: "Beagle",
    name_en: "Beagle",
    breed_group: "Sabujos",
    size: "medium",
    coat: "short",
    energy_level: 4,
    grooming_needs: 2,
    trainability: 3,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 3,
    weight_min_kg: 9,
    weight_max_kg: 11,
    height_min_cm: 33,
    height_max_cm: 41,
    life_span_min: 10,
    life_span_max: 15,
    temperament_pt: "Curioso, Amigável, Alegre, Determinado",
    description_pt: "Farejador nato, curioso e brincalhão. Ótimo com crianças e famílias ativas. Pode ser teimoso no treinamento. Vocalização frequente.",
    image_url: null,
  },
  {
    name_pt: "Poodle Toy",
    name_en: "Poodle (Toy)",
    breed_group: "Toy/Companhia",
    size: "small",
    coat: "long",
    energy_level: 3,
    grooming_needs: 5,
    trainability: 5,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 2,
    shedding_level: 1,
    weight_min_kg: 2,
    weight_max_kg: 4,
    height_min_cm: 24,
    height_max_cm: 28,
    life_span_min: 12,
    life_span_max: 15,
    temperament_pt: "Inteligente, Ativo, Instintivo, Alerta",
    description_pt: "Menor versão do Poodle, hipoalergênico e muito inteligente. Excelente para apartamentos e pessoas com alergia. Precisa de tosa profissional frequente.",
    image_url: null,
  },
  {
    name_pt: "Poodle Miniatura",
    name_en: "Poodle (Miniature)",
    breed_group: "Toy/Companhia",
    size: "small",
    coat: "long",
    energy_level: 3,
    grooming_needs: 5,
    trainability: 5,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 1,
    weight_min_kg: 5,
    weight_max_kg: 9,
    height_min_cm: 28,
    height_max_cm: 35,
    life_span_min: 12,
    life_span_max: 15,
    temperament_pt: "Inteligente, Ativo, Elegante, Obediente",
    description_pt: "Versão média do Poodle, hipoalergênico e altamente inteligente. Muito versátil, se adapta bem a diferentes lares e estilos de vida.",
    image_url: null,
  },
  {
    name_pt: "Poodle Standard",
    name_en: "Poodle (Standard)",
    breed_group: "Não Esportivo",
    size: "medium",
    coat: "long",
    energy_level: 3,
    grooming_needs: 5,
    trainability: 5,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 3,
    shedding_level: 1,
    weight_min_kg: 20,
    weight_max_kg: 32,
    height_min_cm: 45,
    height_max_cm: 60,
    life_span_min: 10,
    life_span_max: 13,
    temperament_pt: "Inteligente, Instintivo, Ativo, Elegante",
    description_pt: "Considerado um dos cães mais inteligentes, ativo e versátil. Hipoalergênico, originalmente criado como cão de caça d'água. Destaca-se em obediência e esportes caninos.",
    image_url: null,
  },
  {
    name_pt: "Bulldog Francês",
    name_en: "French Bulldog",
    breed_group: "Não Esportivo",
    size: "small",
    coat: "short",
    energy_level: 2,
    grooming_needs: 2,
    trainability: 3,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 2,
    shedding_level: 2,
    weight_min_kg: 8,
    weight_max_kg: 14,
    height_min_cm: 27,
    height_max_cm: 33,
    life_span_min: 10,
    life_span_max: 12,
    temperament_pt: "Afetuoso, Vivo, Brincalhão, Alerta",
    description_pt: "Companheiro perfeito para apartamentos. Baixa necessidade de exercício e muito afetuoso. Atenção especial à saúde respiratória — não tolera calor extremo.",
    image_url: null,
  },
  {
    name_pt: "Bulldog Inglês",
    name_en: "English Bulldog",
    breed_group: "Não Esportivo",
    size: "medium",
    coat: "short",
    energy_level: 2,
    grooming_needs: 2,
    trainability: 3,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 2,
    shedding_level: 3,
    weight_min_kg: 18,
    weight_max_kg: 25,
    height_min_cm: 31,
    height_max_cm: 40,
    life_span_min: 8,
    life_span_max: 10,
    temperament_pt: "Dócil, Corajoso, Amigável, Calmo",
    description_pt: "Simbólico e afável. Excelente para famílias e apartamentos, mas requer cuidados com as pregas de pele e temperatura. Vai bem com crianças e outros pets.",
    image_url: null,
  },
  {
    name_pt: "Pastor Alemão",
    name_en: "German Shepherd",
    breed_group: "Pastoreio",
    size: "large",
    coat: "medium",
    energy_level: 5,
    grooming_needs: 3,
    trainability: 5,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 5,
    shedding_level: 4,
    weight_min_kg: 22,
    weight_max_kg: 40,
    height_min_cm: 55,
    height_max_cm: 65,
    life_span_min: 9,
    life_span_max: 13,
    temperament_pt: "Inteligente, Leal, Corajoso, Confiante",
    description_pt: "Cão de trabalho por excelência, amplamente usado em operações policiais e militares. Muito inteligente e protetor. Exige espaço, exercício intenso e treinamento consistente.",
    image_url: null,
  },
  {
    name_pt: "Border Collie",
    name_en: "Border Collie",
    breed_group: "Pastoreio",
    size: "medium",
    coat: "medium",
    energy_level: 5,
    grooming_needs: 3,
    trainability: 5,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 5,
    shedding_level: 3,
    weight_min_kg: 12,
    weight_max_kg: 20,
    height_min_cm: 46,
    height_max_cm: 56,
    life_span_min: 12,
    life_span_max: 15,
    temperament_pt: "Inteligente, Energético, Responsivo, Alerta",
    description_pt: "Considerado o cão mais inteligente do mundo. Precisa de estímulo mental constante e muito exercício físico. Ideal para casas com quintal e tutores ativos.",
    image_url: null,
  },
  {
    name_pt: "Rottweiler",
    name_en: "Rottweiler",
    breed_group: "Trabalho",
    size: "large",
    coat: "short",
    energy_level: 3,
    grooming_needs: 2,
    trainability: 4,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 3,
    shedding_level: 2,
    weight_min_kg: 36,
    weight_max_kg: 60,
    height_min_cm: 56,
    height_max_cm: 69,
    life_span_min: 8,
    life_span_max: 10,
    temperament_pt: "Leal, Amoroso, Obediente, Confiante",
    description_pt: "Forte e confiante, excelente guardião da família. Com socialização precoce é dócil e afetuoso. Precisa de treinamento firme e dono experiente.",
    image_url: null,
  },
  {
    name_pt: "Yorkshire Terrier",
    name_en: "Yorkshire Terrier",
    breed_group: "Terrier",
    size: "small",
    coat: "long",
    energy_level: 3,
    grooming_needs: 5,
    trainability: 3,
    friendliness: 4,
    good_with_kids: false,
    good_for_apartments: true,
    exercise_needs: 2,
    shedding_level: 1,
    weight_min_kg: 2,
    weight_max_kg: 3,
    height_min_cm: 17,
    height_max_cm: 23,
    life_span_min: 13,
    life_span_max: 16,
    temperament_pt: "Corajoso, Determinado, Investigativo, Enérgico",
    description_pt: "Pequeno mas cheio de personalidade. Pelo longo e sedoso exige escovação diária. Corajoso e determinado — não sabe que é pequeno. Melhor com crianças maiores.",
    image_url: null,
  },
  {
    name_pt: "Shih Tzu",
    name_en: "Shih Tzu",
    breed_group: "Toy/Companhia",
    size: "small",
    coat: "long",
    energy_level: 2,
    grooming_needs: 5,
    trainability: 3,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 2,
    shedding_level: 1,
    weight_min_kg: 4,
    weight_max_kg: 7,
    height_min_cm: 20,
    height_max_cm: 28,
    life_span_min: 10,
    life_span_max: 16,
    temperament_pt: "Afectuoso, Brincalhão, Fora, Amigável",
    description_pt: "Companheiro dócil e afetuoso, criado para ser cão de palácio. Perfeito para apartamentos e famílias. Pelo longo exige escovação frequente e tosa profissional.",
    image_url: null,
  },
  {
    name_pt: "Maltês",
    name_en: "Maltese",
    breed_group: "Toy/Companhia",
    size: "small",
    coat: "long",
    energy_level: 3,
    grooming_needs: 5,
    trainability: 4,
    friendliness: 5,
    good_with_kids: false,
    good_for_apartments: true,
    exercise_needs: 2,
    shedding_level: 1,
    weight_min_kg: 2,
    weight_max_kg: 4,
    height_min_cm: 20,
    height_max_cm: 25,
    life_span_min: 12,
    life_span_max: 15,
    temperament_pt: "Gentil, Brincalhão, Responsivo, Confiante",
    description_pt: "Elegante e brincalhão, com pelo branco como neve. Não solta pelo — ótimo para alérgicos. Muito apegado ao dono, pode desenvolver ansiedade de separação.",
    image_url: null,
  },
  {
    name_pt: "Lhasa Apso",
    name_en: "Lhasa Apso",
    breed_group: "Não Esportivo",
    size: "small",
    coat: "long",
    energy_level: 3,
    grooming_needs: 5,
    trainability: 3,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 2,
    shedding_level: 1,
    weight_min_kg: 5,
    weight_max_kg: 8,
    height_min_cm: 25,
    height_max_cm: 28,
    life_span_min: 12,
    life_span_max: 15,
    temperament_pt: "Assertivo, Brincalhão, Desconfiado, Leal",
    description_pt: "Independente e leal. Originário do Tibete, era cão de guarda em mosteiros budistas. Excelente para apartamentos, mas desconfiado com estranhos.",
    image_url: null,
  },
  {
    name_pt: "Pug",
    name_en: "Pug",
    breed_group: "Toy/Companhia",
    size: "small",
    coat: "short",
    energy_level: 2,
    grooming_needs: 2,
    trainability: 3,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 2,
    shedding_level: 3,
    weight_min_kg: 6,
    weight_max_kg: 8,
    height_min_cm: 25,
    height_max_cm: 33,
    life_span_min: 12,
    life_span_max: 15,
    temperament_pt: "Encantador, Travesso, Sociável, Tranquilo",
    description_pt: "Expressivo e encantador, ótimo para apartamentos. Personalidade única e muito bem-humorado. Sensível ao calor — evite exercícios intensos em dias quentes.",
    image_url: null,
  },
  {
    name_pt: "Spitz Alemão (Lulu da Pomerânia)",
    name_en: "German Spitz (Pomeranian)",
    breed_group: "Primitivo",
    size: "small",
    coat: "long",
    energy_level: 3,
    grooming_needs: 5,
    trainability: 4,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 4,
    weight_min_kg: 1,
    weight_max_kg: 3,
    height_min_cm: 18,
    height_max_cm: 22,
    life_span_min: 12,
    life_span_max: 16,
    temperament_pt: "Vivo, Brincalhão, Amigável, Inteligente",
    description_pt: "Pequeno e peludo, com personalidade de cão grande. Alerta e vocalizado, ótimo para apartamentos. Pelo duplo exige escovação frequente e solta muito.",
    image_url: null,
  },
  {
    name_pt: "Husky Siberiano",
    name_en: "Siberian Husky",
    breed_group: "Trabalho",
    size: "medium",
    coat: "medium",
    energy_level: 5,
    grooming_needs: 3,
    trainability: 3,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 5,
    shedding_level: 5,
    weight_min_kg: 16,
    weight_max_kg: 27,
    height_min_cm: 50,
    height_max_cm: 60,
    life_span_min: 12,
    life_span_max: 14,
    temperament_pt: "Extrovertido, Amigável, Alerta, Suave",
    description_pt: "Lobo de olhos azuis e temperamento doce. Exige exercício intenso diário e não suporta calor. Muito vocalizado e precisa de espaço amplo.",
    image_url: null,
  },
  {
    name_pt: "Akita Inu",
    name_en: "Akita Inu",
    breed_group: "Primitivo",
    size: "large",
    coat: "medium",
    energy_level: 3,
    grooming_needs: 3,
    trainability: 3,
    friendliness: 3,
    good_with_kids: false,
    good_for_apartments: false,
    exercise_needs: 3,
    shedding_level: 3,
    weight_min_kg: 32,
    weight_max_kg: 45,
    height_min_cm: 58,
    height_max_cm: 67,
    life_span_min: 10,
    life_span_max: 13,
    temperament_pt: "Alerta, Responsivo, Digno, Corajoso",
    description_pt: "Símbolo nacional japonês de lealdade. Independente e reservado com estranhos. Exige socialização precoce e dono experiente. Fiel a um único tutor.",
    image_url: null,
  },
  {
    name_pt: "Chow Chow",
    name_en: "Chow Chow",
    breed_group: "Primitivo",
    size: "medium",
    coat: "long",
    energy_level: 2,
    grooming_needs: 5,
    trainability: 2,
    friendliness: 3,
    good_with_kids: false,
    good_for_apartments: false,
    exercise_needs: 3,
    shedding_level: 4,
    weight_min_kg: 20,
    weight_max_kg: 32,
    height_min_cm: 43,
    height_max_cm: 51,
    life_span_min: 8,
    life_span_max: 12,
    temperament_pt: "Independente, Leal, Reservado, Quieto",
    description_pt: "Uma das raças mais antigas do mundo. Cara de urso, língua azul e personalidade felina. Leal ao dono mas reservado com estranhos. Pelo denso exige cuidados intensos.",
    image_url: null,
  },
  {
    name_pt: "Dachshund (Teckel)",
    name_en: "Dachshund",
    breed_group: "Sabujos",
    size: "small",
    coat: "short",
    energy_level: 3,
    grooming_needs: 2,
    trainability: 3,
    friendliness: 4,
    good_with_kids: false,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 2,
    weight_min_kg: 5,
    weight_max_kg: 9,
    height_min_cm: 20,
    height_max_cm: 27,
    life_span_min: 12,
    life_span_max: 16,
    temperament_pt: "Corajoso, Vivaz, Obstinado, Esperto",
    description_pt: "O popular basset salsicha. Corpo longo, pernas curtas e personalidade gigante. Corajoso e às vezes teimoso. Propenso a problemas de coluna — evite escadas.",
    image_url: null,
  },
  {
    name_pt: "Schnauzer Miniatura",
    name_en: "Miniature Schnauzer",
    breed_group: "Terrier",
    size: "small",
    coat: "medium",
    energy_level: 4,
    grooming_needs: 3,
    trainability: 5,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 1,
    weight_min_kg: 5,
    weight_max_kg: 8,
    height_min_cm: 30,
    height_max_cm: 36,
    life_span_min: 12,
    life_span_max: 14,
    temperament_pt: "Amigável, Esperto, Obediente, Alerta",
    description_pt: "Versão compacta do Schnauzer, ideal para apartamentos. Não solta pelo, muito inteligente e fácil de treinar. Excelente cão de família com personalidade marcante.",
    image_url: null,
  },
  {
    name_pt: "Schnauzer Standard",
    name_en: "Standard Schnauzer",
    breed_group: "Trabalho",
    size: "medium",
    coat: "medium",
    energy_level: 4,
    grooming_needs: 3,
    trainability: 5,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 1,
    weight_min_kg: 14,
    weight_max_kg: 20,
    height_min_cm: 43,
    height_max_cm: 51,
    life_span_min: 13,
    life_span_max: 16,
    temperament_pt: "Esperto, Robusto, Brincalhão, Obstinado",
    description_pt: "Versão original do Schnauzer. Robusto, enérgico e muito inteligente. Excelente cão de guarda e companhia. Treino firme e consistente desde filhote.",
    image_url: null,
  },
  {
    name_pt: "Schnauzer Gigante",
    name_en: "Giant Schnauzer",
    breed_group: "Trabalho",
    size: "large",
    coat: "medium",
    energy_level: 4,
    grooming_needs: 3,
    trainability: 5,
    friendliness: 3,
    good_with_kids: false,
    good_for_apartments: false,
    exercise_needs: 5,
    shedding_level: 1,
    weight_min_kg: 25,
    weight_max_kg: 48,
    height_min_cm: 58,
    height_max_cm: 70,
    life_span_min: 10,
    life_span_max: 12,
    temperament_pt: "Leal, Alerta, Inteligente, Dominante",
    description_pt: "Maior dos três Schnauzers, usado em forças policiais e militares. Muito inteligente e dominante — exige dono experiente, treinamento sólido e exercício intenso.",
    image_url: null,
  },
  {
    name_pt: "Boxer",
    name_en: "Boxer",
    breed_group: "Trabalho",
    size: "large",
    coat: "short",
    energy_level: 4,
    grooming_needs: 2,
    trainability: 4,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 3,
    weight_min_kg: 25,
    weight_max_kg: 32,
    height_min_cm: 53,
    height_max_cm: 63,
    life_span_min: 10,
    life_span_max: 12,
    temperament_pt: "Brincalhão, Enérgico, Leal, Inteligente",
    description_pt: "Energético e leal, ótimo com crianças. Ficou eternamente jovem em personalidade — muito brincalhão. Precisa de exercício diário intenso e socialização precoce.",
    image_url: null,
  },
  {
    name_pt: "Dobermann",
    name_en: "Doberman Pinscher",
    breed_group: "Trabalho",
    size: "large",
    coat: "short",
    energy_level: 4,
    grooming_needs: 2,
    trainability: 5,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 2,
    weight_min_kg: 32,
    weight_max_kg: 45,
    height_min_cm: 61,
    height_max_cm: 72,
    life_span_min: 10,
    life_span_max: 13,
    temperament_pt: "Leal, Obediente, Enérgico, Confiante",
    description_pt: "Elegante e corajoso, um dos melhores cães de guarda. Com socialização adequada é muito afetuoso com a família. Precisa de exercício intenso e estimulação mental.",
    image_url: null,
  },
  {
    name_pt: "Pit Bull Terrier",
    name_en: "American Pit Bull Terrier",
    breed_group: "Terrier",
    size: "medium",
    coat: "short",
    energy_level: 4,
    grooming_needs: 2,
    trainability: 4,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 2,
    weight_min_kg: 14,
    weight_max_kg: 27,
    height_min_cm: 43,
    height_max_cm: 53,
    life_span_min: 12,
    life_span_max: 16,
    temperament_pt: "Corajoso, Afetuoso, Leal, Confiante",
    description_pt: "Com socialização adequada é um cão extremamente afetuoso e leal à família. Altamente enérgico, precisa de exercício intenso e dono firme com experiência canina.",
    image_url: null,
  },
  {
    name_pt: "American Bully",
    name_en: "American Bully",
    breed_group: "Terrier",
    size: "medium",
    coat: "short",
    energy_level: 3,
    grooming_needs: 2,
    trainability: 4,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 3,
    shedding_level: 2,
    weight_min_kg: 20,
    weight_max_kg: 40,
    height_min_cm: 33,
    height_max_cm: 50,
    life_span_min: 10,
    life_span_max: 13,
    temperament_pt: "Gentil, Confiante, Leal, Carinhoso",
    description_pt: "Raça relativamente nova, criada para ser um companheiro familiar. Aparência imponente mas temperamento dócil e carinhoso. Muito afetuoso com crianças.",
    image_url: null,
  },
  {
    name_pt: "Cocker Spaniel Americano",
    name_en: "American Cocker Spaniel",
    breed_group: "Esportivo",
    size: "small",
    coat: "long",
    energy_level: 3,
    grooming_needs: 5,
    trainability: 4,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 2,
    weight_min_kg: 10,
    weight_max_kg: 13,
    height_min_cm: 34,
    height_max_cm: 38,
    life_span_min: 12,
    life_span_max: 15,
    temperament_pt: "Alegre, Gentil, Inteligente, Responsivo",
    description_pt: "Alegre e afável, adora crianças. Pelo longo e sedoso precisa de tosa e escovação frequente. Um dos cães mais populares do Brasil por décadas.",
    image_url: null,
  },
  {
    name_pt: "Cocker Spaniel Inglês",
    name_en: "English Cocker Spaniel",
    breed_group: "Esportivo",
    size: "small",
    coat: "medium",
    energy_level: 4,
    grooming_needs: 4,
    trainability: 5,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 2,
    weight_min_kg: 12,
    weight_max_kg: 15,
    height_min_cm: 38,
    height_max_cm: 43,
    life_span_min: 12,
    life_span_max: 14,
    temperament_pt: "Alegre, Afável, Sociável, Fiel",
    description_pt: "Ligeiramente maior que o americano, mais atlético e com instinto de caça mais aguçado. Muito sociável, precisa de bastante exercício e interação social.",
    image_url: null,
  },
  {
    name_pt: "Cavalier King Charles Spaniel",
    name_en: "Cavalier King Charles Spaniel",
    breed_group: "Toy/Companhia",
    size: "small",
    coat: "medium",
    energy_level: 2,
    grooming_needs: 3,
    trainability: 4,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 2,
    shedding_level: 2,
    weight_min_kg: 5,
    weight_max_kg: 8,
    height_min_cm: 30,
    height_max_cm: 33,
    life_span_min: 9,
    life_span_max: 15,
    temperament_pt: "Gracioso, Gentil, Afetuoso, Sociável",
    description_pt: "Um dos cães de companhia mais gentis. Extremamente afetuoso e se adapta ao estilo de vida do tutor — ativo ou sedentário. Ótimo para famílias com crianças pequenas.",
    image_url: null,
  },
  {
    name_pt: "Bernese Mountain Dog",
    name_en: "Bernese Mountain Dog",
    breed_group: "Trabalho",
    size: "large",
    coat: "long",
    energy_level: 3,
    grooming_needs: 4,
    trainability: 4,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 3,
    shedding_level: 4,
    weight_min_kg: 32,
    weight_max_kg: 52,
    height_min_cm: 58,
    height_max_cm: 70,
    life_span_min: 7,
    life_span_max: 10,
    temperament_pt: "Leal, Afetuoso, Inteligente, Paciente",
    description_pt: "Gigante gentil tricolor, perfeito para famílias. Muito paciente com crianças. Infelizmente tem vida curta. Solta muito pelo e não tolera calor intenso.",
    image_url: null,
  },
  {
    name_pt: "São Bernardo",
    name_en: "Saint Bernard",
    breed_group: "Trabalho",
    size: "giant",
    coat: "medium",
    energy_level: 2,
    grooming_needs: 3,
    trainability: 3,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 2,
    shedding_level: 3,
    weight_min_kg: 65,
    weight_max_kg: 120,
    height_min_cm: 65,
    height_max_cm: 90,
    life_span_min: 8,
    life_span_max: 10,
    temperament_pt: "Gentil, Amigável, Paciente, Obediente",
    description_pt: "Gigante gentil e paciente, famoso por resgates nos Alpes. Excelente com crianças, mas o tamanho exige espaço e comida em grande quantidade.",
    image_url: null,
  },
  {
    name_pt: "Dálmata",
    name_en: "Dalmatian",
    breed_group: "Não Esportivo",
    size: "large",
    coat: "short",
    energy_level: 5,
    grooming_needs: 2,
    trainability: 4,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 5,
    shedding_level: 3,
    weight_min_kg: 20,
    weight_max_kg: 32,
    height_min_cm: 54,
    height_max_cm: 62,
    life_span_min: 11,
    life_span_max: 13,
    temperament_pt: "Sensível, Energético, Amigável, Reservado",
    description_pt: "Iconicamente malhado, muito enérgico e precisa de corridas diárias. Sensível ao clima — filhotes surdos são relativamente comuns. Precisa de socialização cuidadosa.",
    image_url: null,
  },
  {
    name_pt: "Weimaraner",
    name_en: "Weimaraner",
    breed_group: "Esportivo",
    size: "large",
    coat: "short",
    energy_level: 5,
    grooming_needs: 2,
    trainability: 5,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 5,
    shedding_level: 2,
    weight_min_kg: 25,
    weight_max_kg: 40,
    height_min_cm: 56,
    height_max_cm: 69,
    life_span_min: 11,
    life_span_max: 14,
    temperament_pt: "Amigável, Obediente, Alerta, Enérgico",
    description_pt: "Fantasma cinza de olhos penetrantes. Extremamente ativo e precisa de corrida diária intensa. Ansioso se deixado sozinho por muito tempo. Excelente cão de caça.",
    image_url: null,
  },
  {
    name_pt: "Pointer Inglês",
    name_en: "Pointer",
    breed_group: "Esportivo",
    size: "large",
    coat: "short",
    energy_level: 5,
    grooming_needs: 2,
    trainability: 4,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 5,
    shedding_level: 2,
    weight_min_kg: 20,
    weight_max_kg: 34,
    height_min_cm: 54,
    height_max_cm: 62,
    life_span_min: 12,
    life_span_max: 14,
    temperament_pt: "Amigável, Ativo, Obediente, Leal",
    description_pt: "Cão de caça por excelência, atlético e resistente. Precisa de exercício intenso diário. Gentil e bom com crianças em ambiente familiar ativo.",
    image_url: null,
  },
  {
    name_pt: "Setter Irlandês",
    name_en: "Irish Setter",
    breed_group: "Esportivo",
    size: "large",
    coat: "long",
    energy_level: 5,
    grooming_needs: 3,
    trainability: 4,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 5,
    shedding_level: 2,
    weight_min_kg: 25,
    weight_max_kg: 32,
    height_min_cm: 55,
    height_max_cm: 67,
    life_span_min: 12,
    life_span_max: 14,
    temperament_pt: "Enérgico, Brincalhão, Afável, Independente",
    description_pt: "Deslumbrante pelo ruivo e personalidade exuberante. Muito energético e precisa de espaço para correr. Sociável e eterno filhote em espírito.",
    image_url: null,
  },
  {
    name_pt: "Setter Gordon",
    name_en: "Gordon Setter",
    breed_group: "Esportivo",
    size: "large",
    coat: "long",
    energy_level: 4,
    grooming_needs: 3,
    trainability: 4,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 2,
    weight_min_kg: 20,
    weight_max_kg: 36,
    height_min_cm: 58,
    height_max_cm: 66,
    life_span_min: 10,
    life_span_max: 12,
    temperament_pt: "Confiante, Leal, Obstinado, Alerta",
    description_pt: "O maior dos Setters, preto e fogo. Mais reservado que o Irlandês mas igualmente leal. Excelente cão de caça e família para tutores ativos.",
    image_url: null,
  },
  {
    name_pt: "Flat-Coated Retriever",
    name_en: "Flat-Coated Retriever",
    breed_group: "Esportivo",
    size: "large",
    coat: "medium",
    energy_level: 4,
    grooming_needs: 3,
    trainability: 5,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 2,
    weight_min_kg: 25,
    weight_max_kg: 36,
    height_min_cm: 56,
    height_max_cm: 62,
    life_span_min: 8,
    life_span_max: 10,
    temperament_pt: "Otimista, Alegre, Confiante, Sociável",
    description_pt: "O eterno filhote entre os retrievers. Extremamente alegre e sociável, raramente se torna sério. Lamentavelmente vida curta — exige exames periódicos de saúde.",
    image_url: null,
  },
  {
    name_pt: "Jack Russell Terrier",
    name_en: "Jack Russell Terrier",
    breed_group: "Terrier",
    size: "small",
    coat: "short",
    energy_level: 5,
    grooming_needs: 2,
    trainability: 3,
    friendliness: 4,
    good_with_kids: false,
    good_for_apartments: false,
    exercise_needs: 5,
    shedding_level: 2,
    weight_min_kg: 5,
    weight_max_kg: 8,
    height_min_cm: 25,
    height_max_cm: 38,
    life_span_min: 13,
    life_span_max: 16,
    temperament_pt: "Enérgico, Inteligente, Independente, Atlético",
    description_pt: "Pequeno mas com energia inesgotável. Inteligente e independente — pode ser difícil de treinar. Não é para tutores de primeira viagem. Precisa de muito exercício.",
    image_url: null,
  },
  {
    name_pt: "Fox Terrier",
    name_en: "Wire Fox Terrier",
    breed_group: "Terrier",
    size: "small",
    coat: "medium",
    energy_level: 4,
    grooming_needs: 3,
    trainability: 4,
    friendliness: 4,
    good_with_kids: false,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 2,
    weight_min_kg: 7,
    weight_max_kg: 9,
    height_min_cm: 35,
    height_max_cm: 40,
    life_span_min: 12,
    life_span_max: 15,
    temperament_pt: "Alerta, Animado, Ativo, Sociável",
    description_pt: "Terrier clássico, animado e cheio de energia. Excelente farejador com instinto de caça aguçado. Precisa de exercício e não se dá bem com outros cães pequenos.",
    image_url: null,
  },
  {
    name_pt: "West Highland White Terrier",
    name_en: "West Highland White Terrier",
    breed_group: "Terrier",
    size: "small",
    coat: "medium",
    energy_level: 4,
    grooming_needs: 4,
    trainability: 3,
    friendliness: 4,
    good_with_kids: false,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 2,
    weight_min_kg: 6,
    weight_max_kg: 10,
    height_min_cm: 25,
    height_max_cm: 28,
    life_span_min: 12,
    life_span_max: 16,
    temperament_pt: "Alegre, Confiante, Independente, Alerta",
    description_pt: "Pequeno terrier branco escocês, muito popular. Independente mas afetuoso. Pode ser teimoso — treinamento desde filhote é essencial. Lida melhor com crianças maiores.",
    image_url: null,
  },
  {
    name_pt: "Scottish Terrier",
    name_en: "Scottish Terrier",
    breed_group: "Terrier",
    size: "small",
    coat: "medium",
    energy_level: 3,
    grooming_needs: 4,
    trainability: 3,
    friendliness: 3,
    good_with_kids: false,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 2,
    weight_min_kg: 8,
    weight_max_kg: 10,
    height_min_cm: 25,
    height_max_cm: 28,
    life_span_min: 11,
    life_span_max: 13,
    temperament_pt: "Independente, Esperto, Alerta, Leal",
    description_pt: "Compacto e digno, o Scottie é famoso por sua independência e personalidade forte. Desconfiado de estranhos. Mais adequado para adultos do que crianças.",
    image_url: null,
  },
  {
    name_pt: "Terrier Brasileiro",
    name_en: "Brazilian Terrier",
    breed_group: "Terrier",
    size: "small",
    coat: "short",
    energy_level: 4,
    grooming_needs: 2,
    trainability: 4,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 2,
    weight_min_kg: 6,
    weight_max_kg: 10,
    height_min_cm: 33,
    height_max_cm: 40,
    life_span_min: 12,
    life_span_max: 14,
    temperament_pt: "Leal, Ativo, Alerta, Inteligente",
    description_pt: "Única raça criada no Brasil. Ágil, inteligente e muito ativo. Excelente para famílias com espaço externo. Fácil de manter — pelo curto e resistente.",
    image_url: null,
  },
  {
    name_pt: "Rat Terrier",
    name_en: "Rat Terrier",
    breed_group: "Terrier",
    size: "small",
    coat: "short",
    energy_level: 4,
    grooming_needs: 2,
    trainability: 4,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 2,
    weight_min_kg: 4,
    weight_max_kg: 11,
    height_min_cm: 25,
    height_max_cm: 46,
    life_span_min: 12,
    life_span_max: 18,
    temperament_pt: "Leal, Alerta, Curioso, Amoroso",
    description_pt: "Terrier americano de fazenda, muito inteligente e versátil. Longa vida útil, fácil de manter. Bom com crianças e outros animais quando socializado cedo.",
    image_url: null,
  },
  {
    name_pt: "Bull Terrier",
    name_en: "Bull Terrier",
    breed_group: "Terrier",
    size: "medium",
    coat: "short",
    energy_level: 4,
    grooming_needs: 2,
    trainability: 3,
    friendliness: 5,
    good_with_kids: false,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 2,
    weight_min_kg: 22,
    weight_max_kg: 38,
    height_min_cm: 45,
    height_max_cm: 55,
    life_span_min: 11,
    life_span_max: 14,
    temperament_pt: "Brincalhão, Ativo, Protetor, Obstinado",
    description_pt: "Cabeça oval inconfundível e personalidade exuberante. Muito brincalhão e enérgico. Pode ser obstinado — precisa de dono firme com experiência. Melhor com crianças maiores.",
    image_url: null,
  },
  {
    name_pt: "Staffordshire Bull Terrier",
    name_en: "Staffordshire Bull Terrier",
    breed_group: "Terrier",
    size: "medium",
    coat: "short",
    energy_level: 4,
    grooming_needs: 2,
    trainability: 4,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 2,
    weight_min_kg: 11,
    weight_max_kg: 17,
    height_min_cm: 35,
    height_max_cm: 41,
    life_span_min: 12,
    life_span_max: 14,
    temperament_pt: "Corajoso, Confiável, Afectuoso, Leal",
    description_pt: "Chamado de babá inglesa pela paciência com crianças. Muito afetuoso e leal. Robusto e atlético — precisa de exercício intenso e dono presente.",
    image_url: null,
  },
  {
    name_pt: "Bichon Frisé",
    name_en: "Bichon Frise",
    breed_group: "Não Esportivo",
    size: "small",
    coat: "long",
    energy_level: 3,
    grooming_needs: 5,
    trainability: 4,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 1,
    weight_min_kg: 5,
    weight_max_kg: 10,
    height_min_cm: 23,
    height_max_cm: 30,
    life_span_min: 12,
    life_span_max: 15,
    temperament_pt: "Alegre, Gentil, Sensível, Brincalhão",
    description_pt: "Bolinha branca de alegria. Hipoalergênico e ótimo para apartamentos. Muito sociável e não tolera ficar sozinho por longos períodos. Tosa profissional frequente.",
    image_url: null,
  },
  {
    name_pt: "Havanese",
    name_en: "Havanese",
    breed_group: "Toy/Companhia",
    size: "small",
    coat: "long",
    energy_level: 3,
    grooming_needs: 4,
    trainability: 4,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 1,
    weight_min_kg: 3,
    weight_max_kg: 6,
    height_min_cm: 22,
    height_max_cm: 28,
    life_span_min: 14,
    life_span_max: 16,
    temperament_pt: "Inteligente, Responsivo, Brincalhão, Afetuoso",
    description_pt: "Cão nacional de Cuba, alegre e sociável. Hipoalergênico e ideal para apartamentos. Adora aprender truques e é muito sensível ao humor do dono.",
    image_url: null,
  },
  {
    name_pt: "Papillon",
    name_en: "Papillon",
    breed_group: "Toy/Companhia",
    size: "small",
    coat: "long",
    energy_level: 4,
    grooming_needs: 3,
    trainability: 5,
    friendliness: 5,
    good_with_kids: false,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 2,
    weight_min_kg: 3,
    weight_max_kg: 5,
    height_min_cm: 20,
    height_max_cm: 28,
    life_span_min: 13,
    life_span_max: 15,
    temperament_pt: "Alegre, Amigável, Enérgico, Alerta",
    description_pt: "Orelhas em forma de borboleta e inteligência acima da média. Um dos menores cães de agilidade do mundo. Fácil de treinar mas frágil para crianças pequenas.",
    image_url: null,
  },
  {
    name_pt: "Coton de Tulear",
    name_en: "Coton de Tulear",
    breed_group: "Toy/Companhia",
    size: "small",
    coat: "long",
    energy_level: 3,
    grooming_needs: 4,
    trainability: 4,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 1,
    weight_min_kg: 4,
    weight_max_kg: 6,
    height_min_cm: 25,
    height_max_cm: 30,
    life_span_min: 14,
    life_span_max: 16,
    temperament_pt: "Alegre, Afectuoso, Inteligente, Sociável",
    description_pt: "Pelo macio como algodão, muito alegre e adaptável. Hipoalergênico e excelente para apartamentos. Quase não solta pelo — ótimo para alérgicos.",
    image_url: null,
  },
  {
    name_pt: "Chihuahua",
    name_en: "Chihuahua",
    breed_group: "Toy/Companhia",
    size: "small",
    coat: "short",
    energy_level: 3,
    grooming_needs: 2,
    trainability: 3,
    friendliness: 3,
    good_with_kids: false,
    good_for_apartments: true,
    exercise_needs: 2,
    shedding_level: 2,
    weight_min_kg: 1,
    weight_max_kg: 3,
    height_min_cm: 15,
    height_max_cm: 23,
    life_span_min: 12,
    life_span_max: 20,
    temperament_pt: "Leal, Corajoso, Alerta, Vivaz",
    description_pt: "Menor raça do mundo, mas com personalidade gigante. Muito leal ao tutor, desconfiado de estranhos. Frágil para crianças pequenas. Longa vida útil.",
    image_url: null,
  },
  {
    name_pt: "Pequinês",
    name_en: "Pekingese",
    breed_group: "Toy/Companhia",
    size: "small",
    coat: "long",
    energy_level: 1,
    grooming_needs: 5,
    trainability: 2,
    friendliness: 3,
    good_with_kids: false,
    good_for_apartments: true,
    exercise_needs: 1,
    shedding_level: 3,
    weight_min_kg: 3,
    weight_max_kg: 6,
    height_min_cm: 15,
    height_max_cm: 23,
    life_span_min: 12,
    life_span_max: 14,
    temperament_pt: "Afetuoso, Nobre, Temperamental, Obstinado",
    description_pt: "Cão imperial chinês com personalidade real. Independente e pode ser teimoso. Pelo longo exige escovação constante. Sensível ao calor e não tolera exercícios intensos.",
    image_url: null,
  },
  {
    name_pt: "Affenpinscher",
    name_en: "Affenpinscher",
    breed_group: "Toy/Companhia",
    size: "small",
    coat: "medium",
    energy_level: 3,
    grooming_needs: 3,
    trainability: 3,
    friendliness: 4,
    good_with_kids: false,
    good_for_apartments: true,
    exercise_needs: 2,
    shedding_level: 1,
    weight_min_kg: 3,
    weight_max_kg: 5,
    height_min_cm: 23,
    height_max_cm: 30,
    life_span_min: 12,
    life_span_max: 15,
    temperament_pt: "Travesso, Curioso, Animado, Obstinado",
    description_pt: "Cara de macaco e personalidade enorme. Pequeno mas corajoso — não teme cães maiores. Engraçado e muito curioso. Bom para apartamentos, melhor com adultos.",
    image_url: null,
  },
  {
    name_pt: "Pinscher Miniatura",
    name_en: "Miniature Pinscher",
    breed_group: "Toy/Companhia",
    size: "small",
    coat: "short",
    energy_level: 4,
    grooming_needs: 2,
    trainability: 3,
    friendliness: 4,
    good_with_kids: false,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 2,
    weight_min_kg: 4,
    weight_max_kg: 5,
    height_min_cm: 25,
    height_max_cm: 30,
    life_span_min: 14,
    life_span_max: 15,
    temperament_pt: "Enérgico, Responsivo, Brincalhão, Obstinado",
    description_pt: "Dobermann em miniatura — porte pequeno, personalidade intensa. Muito enérgico e alerta. Melhor com crianças maiores. Apesar do tamanho, não é para tutores passivos.",
    image_url: null,
  },
  {
    name_pt: "Boston Terrier",
    name_en: "Boston Terrier",
    breed_group: "Não Esportivo",
    size: "small",
    coat: "short",
    energy_level: 3,
    grooming_needs: 2,
    trainability: 4,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 2,
    weight_min_kg: 5,
    weight_max_kg: 11,
    height_min_cm: 25,
    height_max_cm: 38,
    life_span_min: 11,
    life_span_max: 13,
    temperament_pt: "Amigável, Vivo, Inteligente, Gentil",
    description_pt: "Cavalheiro americano de gravata borboleta. Muito amigável e fácil de cuidar. Ótimo para apartamentos. Pode roncar e tem problemas respiratórios — não tolera calor.",
    image_url: null,
  },
  {
    name_pt: "Shar Pei",
    name_en: "Chinese Shar Pei",
    breed_group: "Não Esportivo",
    size: "medium",
    coat: "short",
    energy_level: 2,
    grooming_needs: 3,
    trainability: 3,
    friendliness: 3,
    good_with_kids: false,
    good_for_apartments: false,
    exercise_needs: 3,
    shedding_level: 2,
    weight_min_kg: 20,
    weight_max_kg: 27,
    height_min_cm: 44,
    height_max_cm: 51,
    life_span_min: 8,
    life_span_max: 12,
    temperament_pt: "Leal, Independente, Reservado, Calmo",
    description_pt: "Cheio de rugas e dignidade. Muito leal ao dono mas desconfiado de estranhos. Requer limpeza frequente entre as pregas de pele para evitar infecções.",
    image_url: null,
  },
  {
    name_pt: "Basenji",
    name_en: "Basenji",
    breed_group: "Primitivo",
    size: "medium",
    coat: "short",
    energy_level: 4,
    grooming_needs: 1,
    trainability: 3,
    friendliness: 3,
    good_with_kids: false,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 1,
    weight_min_kg: 9,
    weight_max_kg: 11,
    height_min_cm: 38,
    height_max_cm: 43,
    life_span_min: 13,
    life_span_max: 14,
    temperament_pt: "Curioso, Travesso, Alerta, Enérgico",
    description_pt: "O cão que não late — vocaliza com um som único. Uma das raças mais antigas. Muito independente e difícil de treinar. Higiene impecável, se limpa como gato.",
    image_url: null,
  },
  {
    name_pt: "Shiba Inu",
    name_en: "Shiba Inu",
    breed_group: "Primitivo",
    size: "small",
    coat: "medium",
    energy_level: 3,
    grooming_needs: 3,
    trainability: 3,
    friendliness: 3,
    good_with_kids: false,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 3,
    weight_min_kg: 8,
    weight_max_kg: 11,
    height_min_cm: 34,
    height_max_cm: 41,
    life_span_min: 13,
    life_span_max: 16,
    temperament_pt: "Alerta, Ativo, Confiante, Leal",
    description_pt: "Fox japonês de tamanho pequeno e personalidade independente. Muito popular após viralizar na internet. Difícil de treinar — mais parecido com um gato em personalidade.",
    image_url: null,
  },
  {
    name_pt: "Spitz Japonês",
    name_en: "Japanese Spitz",
    breed_group: "Primitivo",
    size: "small",
    coat: "long",
    energy_level: 3,
    grooming_needs: 4,
    trainability: 4,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 3,
    weight_min_kg: 5,
    weight_max_kg: 10,
    height_min_cm: 30,
    height_max_cm: 38,
    life_span_min: 12,
    life_span_max: 16,
    temperament_pt: "Obediente, Brincalhão, Afectuoso, Alerta",
    description_pt: "Nuvem branca japonesa, muito sociável e alegre. Surpreendentemente fácil de manter o pelo branco limpo — tem repelência natural à sujeira. Excelente para famílias.",
    image_url: null,
  },
  {
    name_pt: "Whippet",
    name_en: "Whippet",
    breed_group: "Lebréu",
    size: "medium",
    coat: "short",
    energy_level: 4,
    grooming_needs: 2,
    trainability: 4,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 4,
    shedding_level: 1,
    weight_min_kg: 11,
    weight_max_kg: 18,
    height_min_cm: 44,
    height_max_cm: 51,
    life_span_min: 12,
    life_span_max: 15,
    temperament_pt: "Amigável, Gentil, Quieto, Obediente",
    description_pt: "Velocíssimo mas surpreendentemente gentil e silencioso. Adaptado a apartamentos pois descansa muito entre as corridas. Pelo fino — sensível ao frio.",
    image_url: null,
  },
  {
    name_pt: "Greyhound",
    name_en: "Greyhound",
    breed_group: "Lebréu",
    size: "large",
    coat: "short",
    energy_level: 4,
    grooming_needs: 2,
    trainability: 4,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 4,
    shedding_level: 1,
    weight_min_kg: 27,
    weight_max_kg: 40,
    height_min_cm: 68,
    height_max_cm: 76,
    life_span_min: 10,
    life_span_max: 14,
    temperament_pt: "Gentil, Inteligente, Afectuoso, Atlético",
    description_pt: "O cão mais rápido do mundo, mas adora descansar. Excelente para apartamentos se tiver área para corridas diárias. Muito gentil e silencioso dentro de casa.",
    image_url: null,
  },
  {
    name_pt: "Galgo Espanhol",
    name_en: "Spanish Greyhound",
    breed_group: "Lebréu",
    size: "large",
    coat: "short",
    energy_level: 4,
    grooming_needs: 1,
    trainability: 3,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 4,
    shedding_level: 1,
    weight_min_kg: 20,
    weight_max_kg: 35,
    height_min_cm: 60,
    height_max_cm: 70,
    life_span_min: 12,
    life_span_max: 15,
    temperament_pt: "Gentil, Sensível, Calmo, Leal",
    description_pt: "Lebréu espanhol, muito sensível e carinhoso. Semelhante ao Greyhound mas com temperamento ainda mais reservado. Bom com crianças e adaptado a ambientes menores.",
    image_url: null,
  },
  {
    name_pt: "Fila Brasileiro",
    name_en: "Fila Brasileiro",
    breed_group: "Trabalho",
    size: "giant",
    coat: "short",
    energy_level: 3,
    grooming_needs: 2,
    trainability: 3,
    friendliness: 3,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 3,
    shedding_level: 3,
    weight_min_kg: 40,
    weight_max_kg: 80,
    height_min_cm: 60,
    height_max_cm: 75,
    life_span_min: 9,
    life_span_max: 11,
    temperament_pt: "Leal, Determinado, Corajoso, Desconfiado",
    description_pt: "Raça brasileira criada para guarda e caça. Extremamente leal à família mas muito desconfiado de estranhos. Exige dono experiente e socialização intensa desde filhote.",
    image_url: null,
  },
  {
    name_pt: "Cane Corso",
    name_en: "Cane Corso",
    breed_group: "Trabalho",
    size: "large",
    coat: "short",
    energy_level: 3,
    grooming_needs: 2,
    trainability: 4,
    friendliness: 3,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 3,
    shedding_level: 2,
    weight_min_kg: 40,
    weight_max_kg: 50,
    height_min_cm: 60,
    height_max_cm: 70,
    life_span_min: 9,
    life_span_max: 12,
    temperament_pt: "Leal, Reservado, Calmo, Protetor",
    description_pt: "Molossóide italiano imponente e majestoso. Muito leal à família e excelente guarda. Requer socialização precoce e dono experiente. Não recomendado para iniciantes.",
    image_url: null,
  },
  {
    name_pt: "Dogo Argentino",
    name_en: "Dogo Argentino",
    breed_group: "Trabalho",
    size: "large",
    coat: "short",
    energy_level: 4,
    grooming_needs: 2,
    trainability: 4,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 2,
    weight_min_kg: 35,
    weight_max_kg: 45,
    height_min_cm: 60,
    height_max_cm: 68,
    life_span_min: 9,
    life_span_max: 15,
    temperament_pt: "Leal, Amigável, Enérgico, Protetor",
    description_pt: "Cão branco argentino de grande porte, criado para caça ao javali. Muito leal e protetor. Com socialização adequada é afável com família. Dono experiente é essencial.",
    image_url: null,
  },
  {
    name_pt: "Mastim Napolitano",
    name_en: "Neapolitan Mastiff",
    breed_group: "Trabalho",
    size: "giant",
    coat: "short",
    energy_level: 2,
    grooming_needs: 2,
    trainability: 3,
    friendliness: 3,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 2,
    shedding_level: 3,
    weight_min_kg: 50,
    weight_max_kg: 70,
    height_min_cm: 60,
    height_max_cm: 75,
    life_span_min: 7,
    life_span_max: 9,
    temperament_pt: "Obediente, Dominante, Guardião, Leal",
    description_pt: "Gigante italiano repleto de rugas. Cão de guarda impressionante pela só pela aparência. Exige limpeza frequente das pregas faciais. Dono experiente obrigatório.",
    image_url: null,
  },
  {
    name_pt: "Buldogue Campeiro",
    name_en: "Campeiro Bulldog",
    breed_group: "Trabalho",
    size: "large",
    coat: "short",
    energy_level: 3,
    grooming_needs: 2,
    trainability: 3,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 3,
    shedding_level: 2,
    weight_min_kg: 35,
    weight_max_kg: 50,
    height_min_cm: 53,
    height_max_cm: 58,
    life_span_min: 9,
    life_span_max: 13,
    temperament_pt: "Determinado, Leal, Corajoso, Calmo",
    description_pt: "Bulldog brasileiro criado nas fazendas do sul. Muito rústico e resistente ao clima nacional. Leal e protetor com a família, desconfiado de estranhos.",
    image_url: null,
  },
  {
    name_pt: "Pastor Belga Malinois",
    name_en: "Belgian Malinois",
    breed_group: "Pastoreio",
    size: "large",
    coat: "short",
    energy_level: 5,
    grooming_needs: 2,
    trainability: 5,
    friendliness: 3,
    good_with_kids: false,
    good_for_apartments: false,
    exercise_needs: 5,
    shedding_level: 3,
    weight_min_kg: 20,
    weight_max_kg: 30,
    height_min_cm: 56,
    height_max_cm: 66,
    life_span_min: 14,
    life_span_max: 16,
    temperament_pt: "Confiante, Alerta, Inteligente, Vigilante",
    description_pt: "Usado por forças especiais do mundo todo. Energia e drive de trabalho extremos. Não recomendado para tutores sem experiência. Precisa de exercício intenso e estímulo mental constante.",
    image_url: null,
  },
  {
    name_pt: "Pastor Australiano",
    name_en: "Australian Shepherd",
    breed_group: "Pastoreio",
    size: "medium",
    coat: "medium",
    energy_level: 5,
    grooming_needs: 3,
    trainability: 5,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 5,
    shedding_level: 3,
    weight_min_kg: 16,
    weight_max_kg: 32,
    height_min_cm: 46,
    height_max_cm: 58,
    life_span_min: 12,
    life_span_max: 15,
    temperament_pt: "Inteligente, Ativo, Leal, Protetor",
    description_pt: "Cão de pastoreio muito inteligente e versátil. Muito popular em agility e esportes caninos. Precisa de trabalho mental e físico intenso para não desenvolver comportamentos destrutivos.",
    image_url: null,
  },
  {
    name_pt: "Australian Cattle Dog (Boiadeiro Australiano)",
    name_en: "Australian Cattle Dog",
    breed_group: "Pastoreio",
    size: "medium",
    coat: "short",
    energy_level: 5,
    grooming_needs: 2,
    trainability: 5,
    friendliness: 3,
    good_with_kids: false,
    good_for_apartments: false,
    exercise_needs: 5,
    shedding_level: 2,
    weight_min_kg: 14,
    weight_max_kg: 20,
    height_min_cm: 43,
    height_max_cm: 51,
    life_span_min: 12,
    life_span_max: 16,
    temperament_pt: "Enérgico, Alerta, Leal, Obstinado",
    description_pt: "Cão de trabalho extremamente resistente. Inteligente e precisa de ocupação constante — entedia fácil. Melhor para tutores ativos com espaço e experiência.",
    image_url: null,
  },
  {
    name_pt: "Corgi Pembroke",
    name_en: "Pembroke Welsh Corgi",
    breed_group: "Pastoreio",
    size: "small",
    coat: "medium",
    energy_level: 4,
    grooming_needs: 3,
    trainability: 5,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 4,
    shedding_level: 4,
    weight_min_kg: 10,
    weight_max_kg: 14,
    height_min_cm: 25,
    height_max_cm: 30,
    life_span_min: 12,
    life_span_max: 15,
    temperament_pt: "Animado, Inteligente, Leal, Corajoso",
    description_pt: "Pernas curtas, traseiro fofo e personalidade enorme. Cão da Rainha Elizabeth II. Muito inteligente e fácil de treinar. Solta muito pelo — escovação frequente.",
    image_url: null,
  },
  {
    name_pt: "Corgi Cardigan",
    name_en: "Cardigan Welsh Corgi",
    breed_group: "Pastoreio",
    size: "small",
    coat: "medium",
    energy_level: 3,
    grooming_needs: 3,
    trainability: 5,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 3,
    shedding_level: 3,
    weight_min_kg: 11,
    weight_max_kg: 17,
    height_min_cm: 27,
    height_max_cm: 32,
    life_span_min: 12,
    life_span_max: 15,
    temperament_pt: "Afetuoso, Inteligente, Leal, Alerta",
    description_pt: "O Corgi com cauda — mais antigo que o Pembroke. Ligeiramente mais calmo e reservado. Excelente cão de família para tutores que buscam um pastoreio menos intenso.",
    image_url: null,
  },
  {
    name_pt: "Shetland Sheepdog",
    name_en: "Shetland Sheepdog",
    breed_group: "Pastoreio",
    size: "small",
    coat: "long",
    energy_level: 4,
    grooming_needs: 4,
    trainability: 5,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 4,
    shedding_level: 3,
    weight_min_kg: 6,
    weight_max_kg: 12,
    height_min_cm: 33,
    height_max_cm: 41,
    life_span_min: 12,
    life_span_max: 14,
    temperament_pt: "Leal, Afetuoso, Responsivo, Reservado",
    description_pt: "Mini Collie de inteligência excepcional. Muito sensível ao tom de voz do tutor. Excelente em obediência e agility. Pode ser tímido com estranhos.",
    image_url: null,
  },
  {
    name_pt: "Collie",
    name_en: "Rough Collie",
    breed_group: "Pastoreio",
    size: "large",
    coat: "long",
    energy_level: 3,
    grooming_needs: 4,
    trainability: 5,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 3,
    shedding_level: 4,
    weight_min_kg: 18,
    weight_max_kg: 34,
    height_min_cm: 51,
    height_max_cm: 61,
    life_span_min: 14,
    life_span_max: 16,
    temperament_pt: "Gentil, Inteligente, Leal, Protetor",
    description_pt: "Lassie! Excelente cão de família, muito gentil e paciente. Pelo longo exige escovação frequente. Sensível e responsivo ao tutor, fácil de treinar.",
    image_url: null,
  },
  {
    name_pt: "Komondor",
    name_en: "Komondor",
    breed_group: "Pastoreio",
    size: "large",
    coat: "long",
    energy_level: 2,
    grooming_needs: 5,
    trainability: 3,
    friendliness: 3,
    good_with_kids: false,
    good_for_apartments: false,
    exercise_needs: 2,
    shedding_level: 1,
    weight_min_kg: 40,
    weight_max_kg: 60,
    height_min_cm: 64,
    height_max_cm: 76,
    life_span_min: 10,
    life_span_max: 12,
    temperament_pt: "Leal, Independente, Protetor, Calmo",
    description_pt: "Cão de aparência de esfregão — corda natural que protege do clima e de ataques. Cão de guarda de rebanhos húngaro. Muito independente e desconfiado de estranhos.",
    image_url: null,
  },
  {
    name_pt: "Kuvasz",
    name_en: "Kuvasz",
    breed_group: "Pastoreio",
    size: "large",
    coat: "medium",
    energy_level: 3,
    grooming_needs: 3,
    trainability: 3,
    friendliness: 3,
    good_with_kids: false,
    good_for_apartments: false,
    exercise_needs: 3,
    shedding_level: 3,
    weight_min_kg: 32,
    weight_max_kg: 52,
    height_min_cm: 66,
    height_max_cm: 76,
    life_span_min: 10,
    life_span_max: 12,
    temperament_pt: "Leal, Protetor, Corajoso, Independente",
    description_pt: "Guardião de rebanhos húngaro de pelo branco. Muito leal ao dono mas desconfiado de todos os outros. Requer socialização cuidadosa e experiência com raças guardiãs.",
    image_url: null,
  },
  {
    name_pt: "Samoieda",
    name_en: "Samoyed",
    breed_group: "Trabalho",
    size: "medium",
    coat: "long",
    energy_level: 4,
    grooming_needs: 5,
    trainability: 4,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 5,
    weight_min_kg: 16,
    weight_max_kg: 30,
    height_min_cm: 46,
    height_max_cm: 60,
    life_span_min: 12,
    life_span_max: 14,
    temperament_pt: "Amigável, Gentil, Adaptável, Animado",
    description_pt: "Sorriso eterno e pelo branco de nuvem. Muito amigável e sociável. Solta quantidades épicas de pelo — especialmente na muda. Não tolera calor extremo.",
    image_url: null,
  },
  {
    name_pt: "Malamute do Alaska",
    name_en: "Alaskan Malamute",
    breed_group: "Trabalho",
    size: "large",
    coat: "medium",
    energy_level: 4,
    grooming_needs: 3,
    trainability: 3,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 4,
    weight_min_kg: 34,
    weight_max_kg: 38,
    height_min_cm: 56,
    height_max_cm: 63,
    life_span_min: 10,
    life_span_max: 14,
    temperament_pt: "Brincalhão, Leal, Amigável, Digno",
    description_pt: "Cão de trenó de grande porte, forte e resistente. Muito amigável — não é bom guarda. Solta muito pelo e precisa de exercício intenso. Não combina com clima quente.",
    image_url: null,
  },
  {
    name_pt: "Terra Nova",
    name_en: "Newfoundland",
    breed_group: "Trabalho",
    size: "giant",
    coat: "medium",
    energy_level: 2,
    grooming_needs: 4,
    trainability: 4,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 2,
    shedding_level: 4,
    weight_min_kg: 45,
    weight_max_kg: 68,
    height_min_cm: 63,
    height_max_cm: 74,
    life_span_min: 8,
    life_span_max: 10,
    temperament_pt: "Gentil, Inteligente, Leal, Paciente",
    description_pt: "Gigante gentil e excelente nadador — instinto natural de resgate aquático. Muito paciente com crianças. Baba bastante e solta muito pelo.",
    image_url: null,
  },
  {
    name_pt: "Cão de Água Português",
    name_en: "Portuguese Water Dog",
    breed_group: "Trabalho",
    size: "medium",
    coat: "medium",
    energy_level: 4,
    grooming_needs: 4,
    trainability: 5,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 4,
    shedding_level: 2,
    weight_min_kg: 16,
    weight_max_kg: 25,
    height_min_cm: 43,
    height_max_cm: 57,
    life_span_min: 11,
    life_span_max: 13,
    temperament_pt: "Obediente, Aventureiro, Leal, Bem-humorado",
    description_pt: "Hipoalergênico e excelente nadador. Famoso por ser o cão da família Obama. Ótimo para famílias ativas. Pelo cacheado requer tosa frequente.",
    image_url: null,
  },
  {
    name_pt: "Dogue Alemão",
    name_en: "Great Dane",
    breed_group: "Trabalho",
    size: "giant",
    coat: "short",
    energy_level: 3,
    grooming_needs: 2,
    trainability: 4,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 3,
    shedding_level: 2,
    weight_min_kg: 50,
    weight_max_kg: 80,
    height_min_cm: 71,
    height_max_cm: 86,
    life_span_min: 7,
    life_span_max: 10,
    temperament_pt: "Amigável, Paciente, Confiável, Gentil",
    description_pt: "O maior cão do mundo. Gentil gigante, extremamente afável e bom com crianças. Vida curta. Precisa de alimentação cuidadosa para evitar problemas articulares.",
    image_url: null,
  },
  {
    name_pt: "Mastiff Inglês",
    name_en: "English Mastiff",
    breed_group: "Trabalho",
    size: "giant",
    coat: "short",
    energy_level: 2,
    grooming_needs: 2,
    trainability: 3,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 2,
    shedding_level: 3,
    weight_min_kg: 54,
    weight_max_kg: 100,
    height_min_cm: 67,
    height_max_cm: 91,
    life_span_min: 6,
    life_span_max: 10,
    temperament_pt: "Corajoso, Leal, Carinhoso, Digno",
    description_pt: "Um dos cães mais pesados do mundo. Temperamento surpreendentemente gentil. Baba muito. Vida mais curta que a média. Baixo nível de exercício — não é cão para jogging.",
    image_url: null,
  },
  {
    name_pt: "Akita Americano",
    name_en: "American Akita",
    breed_group: "Trabalho",
    size: "large",
    coat: "medium",
    energy_level: 3,
    grooming_needs: 3,
    trainability: 3,
    friendliness: 3,
    good_with_kids: false,
    good_for_apartments: false,
    exercise_needs: 3,
    shedding_level: 3,
    weight_min_kg: 32,
    weight_max_kg: 66,
    height_min_cm: 61,
    height_max_cm: 71,
    life_span_min: 10,
    life_span_max: 13,
    temperament_pt: "Corajoso, Leal, Digno, Receptivo",
    description_pt: "Maior que o Akita Inu japonês. Muito leal e protetor. Não se dá bem com outros cães. Exige socialização intensiva desde filhote e dono com experiência.",
    image_url: null,
  },
  {
    name_pt: "Bloodhound",
    name_en: "Bloodhound",
    breed_group: "Sabujos",
    size: "large",
    coat: "short",
    energy_level: 3,
    grooming_needs: 2,
    trainability: 3,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 3,
    shedding_level: 2,
    weight_min_kg: 36,
    weight_max_kg: 50,
    height_min_cm: 58,
    height_max_cm: 69,
    life_span_min: 10,
    life_span_max: 12,
    temperament_pt: "Caloroso, Gentil, Afável, Obstinado",
    description_pt: "Melhor narrador do reino animal — faro incomparável. Muito gentil e bom com crianças. Difícil de treinar pois segue o nariz. Orelhas longas e rugas adoráveis.",
    image_url: null,
  },
  {
    name_pt: "Basset Hound",
    name_en: "Basset Hound",
    breed_group: "Sabujos",
    size: "medium",
    coat: "short",
    energy_level: 2,
    grooming_needs: 2,
    trainability: 2,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: true,
    exercise_needs: 2,
    shedding_level: 3,
    weight_min_kg: 20,
    weight_max_kg: 35,
    height_min_cm: 30,
    height_max_cm: 38,
    life_span_min: 10,
    life_span_max: 12,
    temperament_pt: "Gentil, Paciente, Tenaz, Caloroso",
    description_pt: "Orelhas enormes, focinho triste e temperamento gentilíssimo. Muito preguiçoso e obstinado — treino requer muita paciência. Ótimo para apartamentos e famílias calmas.",
    image_url: null,
  },
  {
    name_pt: "Vizsla",
    name_en: "Vizsla",
    breed_group: "Esportivo",
    size: "medium",
    coat: "short",
    energy_level: 5,
    grooming_needs: 2,
    trainability: 5,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 5,
    shedding_level: 2,
    weight_min_kg: 18,
    weight_max_kg: 29,
    height_min_cm: 53,
    height_max_cm: 64,
    life_span_min: 12,
    life_span_max: 15,
    temperament_pt: "Energético, Afetuoso, Leal, Gentil",
    description_pt: "Cão de caça húngaro cor de ferrugem. Muito energético e afetuoso — chamado de cão de velcro. Precisa de exercício intenso. Sofre muito de ansiedade de separação.",
    image_url: null,
  },
  {
    name_pt: "Braco Alemão de Pelo Curto",
    name_en: "German Shorthaired Pointer",
    breed_group: "Esportivo",
    size: "large",
    coat: "short",
    energy_level: 5,
    grooming_needs: 2,
    trainability: 5,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 5,
    shedding_level: 2,
    weight_min_kg: 20,
    weight_max_kg: 32,
    height_min_cm: 53,
    height_max_cm: 64,
    life_span_min: 12,
    life_span_max: 14,
    temperament_pt: "Amigável, Inteligente, Disposto, Enérgico",
    description_pt: "Cão de caça versátil e muito atlético. Precisa de corridas diárias longas. Excelente para famílias ativas ao ar livre. Destaca-se em obediência e esportes caninos.",
    image_url: null,
  },
  {
    name_pt: "Springer Spaniel Inglês",
    name_en: "English Springer Spaniel",
    breed_group: "Esportivo",
    size: "medium",
    coat: "medium",
    energy_level: 4,
    grooming_needs: 3,
    trainability: 5,
    friendliness: 5,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 3,
    weight_min_kg: 16,
    weight_max_kg: 25,
    height_min_cm: 46,
    height_max_cm: 56,
    life_span_min: 12,
    life_span_max: 14,
    temperament_pt: "Obediente, Alegre, Sociável, Amigável",
    description_pt: "Alegre e energético, excelente companheiro para famílias ativas. Muito sociável com pessoas e outros animais. Pelo médio requer escovação regular.",
    image_url: null,
  },
  {
    name_pt: "Rhodesian Ridgeback",
    name_en: "Rhodesian Ridgeback",
    breed_group: "Sabujos",
    size: "large",
    coat: "short",
    energy_level: 4,
    grooming_needs: 2,
    trainability: 3,
    friendliness: 4,
    good_with_kids: true,
    good_for_apartments: false,
    exercise_needs: 4,
    shedding_level: 2,
    weight_min_kg: 29,
    weight_max_kg: 41,
    height_min_cm: 61,
    height_max_cm: 69,
    life_span_min: 10,
    life_span_max: 12,
    temperament_pt: "Digno, Leal, Sensível, Independente",
    description_pt: "Cão africano com crista única no dorso. Criado para rastrear leões. Muito leal mas independente. Requer socialização precoce e dono com liderança firme.",
    image_url: null,
  },
];
