import type { Kennel, Puppy, Breeder, Review, Post } from "@/types";

export const mockKennels: (Kennel & { puppies: Puppy[]; breeders: Breeder[] })[] = [
  {
    id: "1",
    owner_id: "u1",
    name: "Canil Rossetti",
    slug: "canil-rossetti",
    description:
      "35 anos de tradição na criação de raças toy. O canil mais antigo em atividade contínua na região de São Paulo, com foco em saúde, temperamento e conformação com o padrão da raça. Nossos reprodutores são campeões nacionais com testes genéticos completos. Filhotes entregues com 60 dias, microchipados, vacinados e com pedigree CBKC.",
    city: "Itapecerica da Serra",
    state: "SP",
    address: null,
    phone: "(11) 99999-0001",
    email: "contato@canilrossetti.com.br",
    instagram: "@canilrossetti",
    website: "https://canilrossetti.com.br",
    logo_url: null,
    cover_url: null,
    years_active: 35,
    kc_registry: "CBKC #1204",
    kc_entity: "CBKC",
    plan: "premium",
    status: "approved",
    verified_at: "2026-01-15T00:00:00Z",
    breeds: ["Shih Tzu", "Lhasa Apso", "Maltês"],
    facilities_approved: true,
    microchip: true,
    vaccines: true,
    dna_tests: true,
    birth_control: true,
    google_rating: 4.9,
    google_reviews_count: 312,
    fareja_rating: 5.0,
    fareja_reviews_count: 47,
    created_at: "2025-06-01T00:00:00Z",
    updated_at: "2026-04-01T00:00:00Z",
    breeders: [
      { id: "b1", kennel_id: "1", name: "Imperador", breed: "Shih Tzu", sex: "male", registry: "LOF BR-15672", titles: "Multi CH BR, Grand CH", photo_url: null, health_tests: ["Displasia", "Patela", "Cardíaco", "Oftalmológico"], born_at: "2020-03-10" },
      { id: "b2", kennel_id: "1", name: "Princesa", breed: "Shih Tzu", sex: "female", registry: "LOF BR-18901", titles: "CH BR, Best of Breed", photo_url: null, health_tests: ["Displasia", "Patela", "Cardíaco"], born_at: "2021-07-22" },
    ],
    puppies: [
      { id: "p1", kennel_id: "1", name: "Fêmea 1 – Shih Tzu", breed: "Shih Tzu", sex: "female", born_at: "2026-01-20", expected_at: null, price: 4000, status: "available", father_id: "b1", mother_id: "b2", photo_url: null, microchipped: true, vaccinated: true, description: "Pelagem branca e dourada, temperamento dócil" },
      { id: "p2", kennel_id: "1", name: "Macho 1 – Shih Tzu", breed: "Shih Tzu", sex: "male", born_at: "2026-01-20", expected_at: null, price: 3500, status: "available", father_id: "b1", mother_id: "b2", photo_url: null, microchipped: true, vaccinated: true, description: "Pelagem tricolor, muito brincalhão" },
      { id: "p3", kennel_id: "1", name: "Fêmea 2 – Maltês", breed: "Maltês", sex: "female", born_at: "2026-02-10", expected_at: null, price: 5000, status: "available", father_id: null, mother_id: null, photo_url: null, microchipped: true, vaccinated: true, description: "Pelagem branca pura, porte miniatura" },
      { id: "p4", kennel_id: "1", name: "Macho 2 – Lhasa Apso", breed: "Lhasa Apso", sex: "male", born_at: null, expected_at: "2026-06-15", price: 3000, status: "upcoming", father_id: null, mother_id: null, photo_url: null, microchipped: false, vaccinated: false, description: "Previsão para junho/2026" },
    ],
  },
  {
    id: "2",
    owner_id: "u2",
    name: "Canil Estrela do Sul",
    slug: "canil-estrela-do-sul",
    description:
      "Referência em Golden Retrievers há mais de duas décadas. Todos os reprodutores com testes de quadril, cotovelo e exames cardíacos completos. Filhotes entregues com 60 dias, microchipados e com carteira de vacinação completa.",
    city: "São Paulo",
    state: "SP",
    address: null,
    phone: "(11) 99999-0002",
    email: "contato@estreladosul.com.br",
    instagram: "@canilestreladosul",
    website: null,
    logo_url: null,
    cover_url: null,
    years_active: 22,
    kc_registry: "CBKC #4521",
    kc_entity: "CBKC",
    plan: "basic",
    status: "approved",
    verified_at: "2026-02-01T00:00:00Z",
    breeds: ["Golden Retriever", "Labrador Retriever"],
    facilities_approved: true,
    microchip: true,
    vaccines: true,
    dna_tests: true,
    birth_control: true,
    google_rating: 4.8,
    google_reviews_count: 187,
    fareja_rating: 4.9,
    fareja_reviews_count: 31,
    created_at: "2025-08-01T00:00:00Z",
    updated_at: "2026-03-15T00:00:00Z",
    breeders: [
      { id: "b3", kennel_id: "2", name: "Thor", breed: "Golden Retriever", sex: "male", registry: "LOF BR-22145", titles: "CH BR, Grand CH", photo_url: null, health_tests: ["Displasia quadril", "Displasia cotovelo", "Cardíaco"], born_at: "2019-05-12" },
      { id: "b4", kennel_id: "2", name: "Luna", breed: "Golden Retriever", sex: "female", registry: "LOF BR-19832", titles: "CH BR", photo_url: null, health_tests: ["Displasia quadril", "Cardíaco", "Oftalmológico"], born_at: "2020-11-03" },
    ],
    puppies: [
      { id: "p5", kennel_id: "2", name: "Macho 1 – Golden", breed: "Golden Retriever", sex: "male", born_at: "2026-02-15", expected_at: null, price: 5500, status: "available", father_id: "b3", mother_id: "b4", photo_url: null, microchipped: true, vaccinated: true, description: "Pelagem dourada clara, excelente temperamento" },
      { id: "p6", kennel_id: "2", name: "Fêmea 1 – Golden", breed: "Golden Retriever", sex: "female", born_at: "2026-02-15", expected_at: null, price: 6000, status: "reserved", father_id: "b3", mother_id: "b4", photo_url: null, microchipped: true, vaccinated: true, description: "Reservada – pelagem dourada escura" },
      { id: "p7", kennel_id: "2", name: "Macho 2 – Labrador", breed: "Labrador Retriever", sex: "male", born_at: null, expected_at: "2026-05-20", price: 4500, status: "upcoming", father_id: null, mother_id: null, photo_url: null, microchipped: false, vaccinated: false, description: "Previsão para maio/2026" },
    ],
  },
  {
    id: "3",
    owner_id: "u3",
    name: "Von Falkenberg",
    slug: "von-falkenberg",
    description:
      "Criação seletiva de Pastor Alemão com linhagens de trabalho europeias. Filhotes com temperamento equilibrado, testados para displasia e com pedigree internacional. Nosso foco é produzir cães saudáveis e funcionais.",
    city: "Curitiba",
    state: "PR",
    address: null,
    phone: "(41) 99999-0003",
    email: "contato@vonfalkenberg.com.br",
    instagram: "@vonfalkenberg",
    website: "https://vonfalkenberg.com.br",
    logo_url: null,
    cover_url: null,
    years_active: 18,
    kc_registry: "CBKC #3287",
    kc_entity: "CBKC",
    plan: "premium",
    status: "approved",
    verified_at: "2026-01-20T00:00:00Z",
    breeds: ["Pastor Alemão", "Malinois"],
    facilities_approved: true,
    microchip: true,
    vaccines: true,
    dna_tests: true,
    birth_control: true,
    google_rating: 4.8,
    google_reviews_count: 143,
    fareja_rating: 4.8,
    fareja_reviews_count: 22,
    created_at: "2025-07-01T00:00:00Z",
    updated_at: "2026-03-20T00:00:00Z",
    breeders: [
      { id: "b5", kennel_id: "3", name: "Rex vom Haus", breed: "Pastor Alemão", sex: "male", registry: "SZ-234567", titles: "SchH3, KKL1, V-rated", photo_url: null, health_tests: ["HD-A", "ED-normal", "DM-clear"], born_at: "2019-08-01" },
      { id: "b6", kennel_id: "3", name: "Bella", breed: "Pastor Alemão", sex: "female", registry: "LOF BR-21098", titles: "V-rated, BH", photo_url: null, health_tests: ["HD-A", "ED-normal"], born_at: "2021-02-14" },
    ],
    puppies: [
      { id: "p8", kennel_id: "3", name: "Macho 1 – Pastor Alemão", breed: "Pastor Alemão", sex: "male", born_at: "2026-03-01", expected_at: null, price: 7000, status: "available", father_id: "b5", mother_id: "b6", photo_url: null, microchipped: true, vaccinated: true, description: "Capa preta, excelente angulação" },
      { id: "p9", kennel_id: "3", name: "Fêmea 1 – Pastor Alemão", breed: "Pastor Alemão", sex: "female", born_at: "2026-03-01", expected_at: null, price: 8000, status: "reserved", father_id: "b5", mother_id: "b6", photo_url: null, microchipped: true, vaccinated: true, description: "Reservada – linhagem de trabalho" },
    ],
  },
  {
    id: "4",
    owner_id: "u4",
    name: "Canil Terra Dourada",
    slug: "canil-terra-dourada",
    description:
      "Especializado em braquicefálicos com foco em saúde respiratória. Todos os reprodutores passam por avaliação BOAS (Brachycephalic Obstructive Airway Syndrome) antes da reprodução. Referência em Bulldog Francês no sudeste.",
    city: "Belo Horizonte",
    state: "MG",
    address: null,
    phone: "(31) 99999-0004",
    email: "contato@terradourada.com.br",
    instagram: "@terradourada",
    website: null,
    logo_url: null,
    cover_url: null,
    years_active: 12,
    kc_registry: "CBKC #5891",
    kc_entity: "CBKC",
    plan: "basic",
    status: "approved",
    verified_at: "2026-02-10T00:00:00Z",
    breeds: ["Bulldog Francês", "Pug"],
    facilities_approved: true,
    microchip: true,
    vaccines: true,
    dna_tests: true,
    birth_control: true,
    google_rating: 4.7,
    google_reviews_count: 98,
    fareja_rating: 4.7,
    fareja_reviews_count: 15,
    created_at: "2025-09-01T00:00:00Z",
    updated_at: "2026-03-10T00:00:00Z",
    breeders: [
      { id: "b7", kennel_id: "4", name: "Duke", breed: "Bulldog Francês", sex: "male", registry: "LOF BR-25001", titles: "CH BR", photo_url: null, health_tests: ["BOAS grade 0", "Patela", "Coluna"], born_at: "2020-06-15" },
      { id: "b8", kennel_id: "4", name: "Mia", breed: "Bulldog Francês", sex: "female", registry: "LOF BR-23456", titles: "Excelente", photo_url: null, health_tests: ["BOAS grade 0", "Patela"], born_at: "2021-09-20" },
    ],
    puppies: [
      { id: "p10", kennel_id: "4", name: "Macho 1 – Frenchie", breed: "Bulldog Francês", sex: "male", born_at: "2026-02-25", expected_at: null, price: 10000, status: "available", father_id: "b7", mother_id: "b8", photo_url: null, microchipped: true, vaccinated: true, description: "Blue fawn, respiração excelente" },
    ],
  },
];

export const mockReviews: (Review & { user_name: string; user_avatar: string | null })[] = [
  { id: "r1", kennel_id: "1", user_id: "u10", user_name: "Camila S.", user_avatar: null, rating: 5, comment: "Comprei meu Shih Tzu no Canil Rossetti e a experiência foi impecável. O filhote chegou saudável, vacinado e microchipado. A família é muito atenciosa e transparente.", source: "fareja", created_at: "2026-03-15T00:00:00Z" },
  { id: "r2", kennel_id: "1", user_id: "u11", user_name: "Roberto M.", user_avatar: null, rating: 5, comment: "35 anos de experiência fazem diferença. Meu Lhasa Apso é perfeito e veio com toda documentação. Recomendo demais!", source: "fareja", created_at: "2026-02-20T00:00:00Z" },
  { id: "r3", kennel_id: "2", user_id: "u12", user_name: "Fernanda L.", user_avatar: null, rating: 5, comment: "Golden Retriever lindo e saudável! Thor e Luna são reprodutores incríveis. O canil é organizado e limpo.", source: "fareja", created_at: "2026-03-01T00:00:00Z" },
];

export const mockPosts: Post[] = [
  { id: "post1", author_id: "u10", author_name: "Camila S.", author_avatar: null, author_role: "client", kennel_id: null, kennel_name: null, type: "experience", title: "Minha experiência comprando um Shih Tzu na Fareja", content: "Depois de meses pesquisando, encontrei o Canil Rossetti pela Fareja. A diferença de comprar de um canil verificado é enorme. Recebi toda documentação, pedigree e o filhote já microchipado. Hoje meu Thor tem 3 meses e está super saudável!", image_url: null, likes_count: 24, comments_count: 8, created_at: "2026-03-20T00:00:00Z" },
  { id: "post2", author_id: "u1", author_name: "Canil Rossetti", author_avatar: null, author_role: "kennel", kennel_id: "1", kennel_name: "Canil Rossetti", type: "tip", title: "5 sinais de um criador responsável", content: "1. Registro oficial no Kennel Club\n2. Testes genéticos dos reprodutores\n3. Filhotes microchipados\n4. Instalações limpas e espaçosas\n5. Não entrega filhotes antes dos 45-60 dias\n\nSe o criador não atende esses requisitos, desconfie!", image_url: null, likes_count: 56, comments_count: 12, created_at: "2026-03-18T00:00:00Z" },
  { id: "post3", author_id: "u15", author_name: "Lucas P.", author_avatar: null, author_role: "client", kennel_id: null, kennel_name: null, type: "question", title: "Golden Retriever ou Labrador para apartamento?", content: "Moro em apartamento de 70m² e trabalho home office. Estou entre Golden e Labrador. Alguém tem experiência com essas raças em apartamento? O prédio aceita cães de grande porte.", image_url: null, likes_count: 15, comments_count: 23, created_at: "2026-03-22T00:00:00Z" },
];

export const allBreeds = [
  "Shih Tzu",
  "Lhasa Apso",
  "Maltês",
  "Golden Retriever",
  "Labrador Retriever",
  "Pastor Alemão",
  "Malinois",
  "Bulldog Francês",
  "Pug",
];

export const allStates = ["SP", "PR", "MG", "RJ", "RS", "SC", "BA", "PE", "CE", "GO"];
